### ISSUE TITLE
Advanced Particle Analyzer produces Java exception error when run repeatedly inside a for loop

### ISSUE THREAD

**Issue by Volko1** [biovoxxel/BioVoxxel_Toolbox#2]
I am a bit stumped by a Java exception error that appears to be related to the Advanced Particle Analyzer. It doesn't appear to affect the function of the Advanced Particle Analyzer, but it generates a window with an error message. I have written the following small macro code to illustrate the problem:
 

for (k=0; k<3; k++) {

newImage("Test"+k, "8-bit black", 1000, 1000, 1);
for (i=1;i<11;i++){
makeOval(random*1000, random*1000, random*50, random*50);
run("Fill", "slice");
makeLine(random*1000, random*1000,random*1000, random*1000);
  run("Fill", "slice");
};
run("Extended Particle Analyzer", "pixel solidity=0.5-1.00 aspect=0-100 show=Masks redirect=None keep=None display reset");
wait(2000);
rename("Blobs"+k);
imageCalculator("Subtract  create", "Test"+k,"Blobs"+k);
rename("Lines"+k);
close("Blobs"+k);
close("Test"+k);
};

The macro code creates an image containing random lines and ovals. It then uses the Advanced Particle Analyzer to find 'blob' like structures and subtract them from the original image. Carrying out all the commands manually (or just once using the macro code without the outer for loop) produces the expected result without any exceptions.

However, putting the code inside the for-loop to carry it out multiple times (i.e. to batch process a series of images) throws a Java exception (I have copied the error message below) on the second and all subsequent images. 

I thought that this may be a timing issue and added a wait command after the Extended Particle Analyzer command, but it didn't solve the problem.

I have updated ImageJ to the latest version (v1.51r) and also updated the Biovoxxel tools via the Fiji update site, but the issue persists.

Any idea what might be going on?

Thanks,
Volko

Java error message text (doesn't appear to be terminal as code continues):

 
(Fiji Is Just) ImageJ 2.0.0-rc-61/1.51n; Java 1.8.0_66 [64-bit]; Windows 10 10.0; 97MB of 5938MB (1%)
 
java.lang.IllegalArgumentException: "Label" column not found
at ij.measure.ResultsTable.getValue(ResultsTable.java:376)
at Extended_Particle_Analyzer.particleAnalysis(Extended_Particle_Analyzer.java:680)
at Extended_Particle_Analyzer.run(Extended_Particle_Analyzer.java:340)
at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:265)
at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
at ij.IJ.runUserPlugIn(IJ.java:219)
at ij.IJ.runPlugIn(IJ.java:181)
at ij.Executer.runCommand(Executer.java:137)
at ij.Executer.run(Executer.java:66)
at ij.IJ.run(IJ.java:297)
at ij.macro.Functions.doRun(Functions.java:601)
at ij.macro.Functions.doFunction(Functions.java:96)
at ij.macro.Interpreter.doStatement(Interpreter.java:230)
at ij.macro.Interpreter.doBlock(Interpreter.java:608)
at ij.macro.Interpreter.doStatement(Interpreter.java:272)
at ij.macro.Interpreter.doFor(Interpreter.java:530)
at ij.macro.Interpreter.doStatement(Interpreter.java:254)
at ij.macro.Interpreter.doStatements(Interpreter.java:218)
at ij.macro.Interpreter.run(Interpreter.java:115)
at ij.macro.Interpreter.run(Interpreter.java:85)
at ij.macro.Interpreter.run(Interpreter.java:96)
at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
at ij.IJ.runMacro(IJ.java:134)
at ij.IJ.runMacro(IJ.java:123)
at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1052)
at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1048)
at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:999)
at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1048)
at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:136)
at org.scijava.script.ScriptModule.run(ScriptModule.java:159)
at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:237)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by biovoxxel** [comment]
With the BioVoxxel_plugins_1.1.8 this bug should be fixed
